version: '3.2'

services:
  mashnet-node:
    image: kiltprotocol/mashnet-node:0.24.0
    command: '--dev --ws-port 9944 --ws-external'
    ports:
      - 9944:9944
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=registry
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    # ports:
    #   - 27017:27017
  services:
    image: kiltprotocol/demo-services:0.18.0
    environment:
      - NODE_ENV=docker-compose
      - MONGODB_HOST=mongodb://mongodb?authSource=admin
      - MONGODB_USER=mongoadmin
      - MONGODB_PASS=secret
      - FAUCET_ACCOUNT=0xcdfd6024d2b0eba27d54cc92a44cd9a627c69b2dbda15ed7e58085425119ae03
      - BOOT_NODE_ADDRESS=ws://mashnet-node:9944
    ports:
      - 3001:3000
    depends_on:
      - mongodb
      - mashnet-node
  demo-client:
    image: kiltprotocol/demo-client:0.23.0
    environment:
      - REACT_APP_SERVICE_HOST=//127.0.0.1:3001
      - REACT_APP_NODE_HOST=ws://127.0.0.1:9944
      - REACT_APP_FAUCET_URL=http://127.0.0.1:3002
      # if you experience issues where the watcher does not trigger rebuilds
      # when changing files in src/ the following option may help
      #- CHOKIDAR_USEPOLLING=true

    ports:
      - 3000:80
    depends_on:
      - services
      - mashnet-node
