openapi: '3.0.3'
info:
  version: 1.0.0
  title: DENA-BMIL
  description: Documentation for the KILT BMIL application
tags:
  - name: Reset
  - name: Identity
  - name: Claiming
  - name: Credential
paths:
  /reset:
    post:
      tags: [Reset]
      description: Resets the state of the application.
      responses:
        '200':
          description: Application was fully reset.
  /identity:
    post:
      tags:
        - Identity
      description: Endpoint to generate and store a new Identity.
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
    get:
      tags:
        - Identity
      description: Endpoint to get stored Identity address.
      responses:
        '200':
          description: Returns the stored Identitiy address.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
  /identity/register:
    post:
      tags: [Identity]
      description: Registers the stored Identity as a DID.
      responses:
        '200':
          description: DID registered
          content:
            application/json:
              examples:
                DDO:
                  $ref: '#/components/examples/DDO'
  /claim:
    post:
      tags: [Claiming]
      description: Generates a Claim and sends a RequestForAttestation to an Attester.
      responses:
        '200':
          description: Claim successfully generated and sent to the attester.
  /credential:
    get:
      tags: [Credential]
      description: Returns the stored credential
      responses:
        '200':
          description: Returns the stored credential
          content:
            application/json:
              examples:
                Credential:
                  $ref: '#/components/examples/DDO'

components:
  schemas:    
    Identity:
      type: string
      example: '4rAPNc2DPmbL1MWyQxPmaR5TTYta9jexdnLMY34AA32UFpeY'
  examples:
    DDO:
      value:
        id: 'did:kilt:4rAPNc2DPmbL1MWyQxPmaR5TTYta9jexdnLMY34AA32UFpeY'
        '@context': 'https://w3id.org/did/v1'
        authentication:
          - publicKey:
              - 'did:kilt:4rAPNc2DPmbL1MWyQxPmaR5TTYta9jexdnLMY34AA32UFpeY#key-1'
            type: Ed25519SignatureAuthentication2018
        publicKey:
          - controller: 'did:kilt:4rAPNc2DPmbL1MWyQxPmaR5TTYta9jexdnLMY34AA32UFpeY'
            id: 'did:kilt:4rAPNc2DPmbL1MWyQxPmaR5TTYta9jexdnLMY34AA32UFpeY#key-1'
            publicKeyHex: '0x8fa094c521c982567063e0a648369e4b666f669d4ddfa903a048bb6e2c3f1ec6'
            type: Ed25519VerificationKey2018
          - controller: 'did:kilt:4rAPNc2DPmbL1MWyQxPmaR5TTYta9jexdnLMY34AA32UFpeY'
            id: 'did:kilt:4rAPNc2DPmbL1MWyQxPmaR5TTYta9jexdnLMY34AA32UFpeY#key-2'
            publicKeyHex: '0xf4e6a9dce42e748621405998e360c354f6cab5430d459291f92a024e42572b0f'
            type: X25519Salsa20Poly1305Key2018
        service:
          - serviceEndpoint: 'https://services.kilt.io/messaging'
            type: KiltMessagingService
    Credential:
      value:
        request:
          claim:
            cTypeHash: '0x5366521b1cf4497cfe5f17663a7387a87bb8f2c4295d7c40f3140e7ee6afc41b'
            contents:
              name: OLI
              age: 20
            owner: 4orFteGqT2HMbvPQCfg5YVfHA1EPAswHdRqkmCiAcDYHQAr1
          claimHashes:
            - '0x07a2c0b9cf999e248a2a588a2b3198dd659dc40974582a924c036636afce6d27'
            - '0x6f3dfc08de6d270d35278f8cdad0ee8121ce16b2a41474ede8c596785aa5bab6'
            - '0xa986d3f8d488fefbf3b09183688afdc1c063bbbd8e02b8f83d57601c90b12a8b'
          claimNonceMap:
            '0xe6251fa30a4164b90d9a594b9ae894754179ee60c5ea665e64cdcee8b8d4d71b': 1e753631-d732-4c9b-b250-5757a097438a
            '0x79ddfb1d42f6b71685d83f383808af9b273748731eecc78ba758722000378dbc': 699dd99a-38d7-43aa-ae95-b4f59e7ee3e9
            '0x1f0282d2f81c6a38b4fda572c5d1c811c7e4b9fc714e470ff5bab6397f69844c': f58319a7-5358-4d9c-9e9e-edbdefedef39
          legitimations: []
          delegationId: null
          rootHash: '0x748756e1aadb1bb9fcd712cdf269fc2b83ddf466b7a38a7cb1cb437576644a8a'
          claimerSignature: '0x001c24b7427d7af8124094fd74bca3b6b82e1bb5af39b4fad7acfa3ddd4b1208264e3a0d64efd152336e3be768baf97f5807c33b21e050f996a9d0779c0d0ff100'
        attestation:
          claimHash: '0x748756e1aadb1bb9fcd712cdf269fc2b83ddf466b7a38a7cb1cb437576644a8a'
          cTypeHash: '0x5366521b1cf4497cfe5f17663a7387a87bb8f2c4295d7c40f3140e7ee6afc41b'
          delegationId: null
          owner: 4qK4AzHMBQVGKUURU2AJq9Ch8ozgSFEngmo87S7cggqK6kJW
          revoked: false
        

